### PR TITLE
Add validation

### PR DESCRIPTION
**Pull request by johansten**
Adds a function to validate mnemonics for user feedback

### CODE REVIEW

**Comment by chatch** [comment]
nice. would you mind adding a test case for this in here: https://github.com/chatch/stellar-hd-wallet/blob/master/test/stellar-hd-wallet.js too?

**Comment by chatch** [comment]
merged. thanks! 

i'll write the tests for this ..  and will release a new npm version soon.

**Comment by chatch** [comment]
published to npm v0.0.5

**Comment by johansten** [comment]
Awesome, I got side tracked with SBC.

I wish validation was more granular in detecting errors, but then we'd have to go down to the `bip39` level. ¯\_(ツ)_/¯

**Comment by chatch** [comment]
no worries.  do you mean more specific errors returned rather then just false?

**Pull request merged**
